name: Publish

on:
  push:
    branches: [ main ]

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
        
          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Log in to the Container registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push Docker image
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              cache-from: type=registry,ref=ghcr.io/playcanvas/editor-test:cache
              cache-to: type=registry,ref=ghcr.io/playcanvas/editor-test:cache,mode=max
              tags: ghcr.io/playcanvas/editor-test:latest
              platforms: linux/amd64,linux/arm64
            env:
              DOCKER_BUILD_SUMMARY: false
