name: Test

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: true

concurrency:
  group: 'test'
  cancel-in-progress: true

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Editor Testing Suite
        run: |
          docker run \
          --pull always \
          --rm \
          -e PC_HOST=${{ secrets.PC_HOST }} \
          -e PC_LOGIN_HOST=${{ secrets.PC_LOGIN_HOST }} \
          -e PC_LAUNCH_HOST=${{ secrets.PC_LAUNCH_HOST }} \
          -e PC_EMAIL=${{ secrets.PC_EMAIL }} \
          -e PC_PASSWORD=${{ secrets.PC_PASSWORD }} \
          ghcr.io/playcanvas/editor-test:latest
